### ISSUE TITLE
Config not found

### ISSUE THREAD

**Issue by ipwnponies** [edmundmok/mealpy#22]
`FileNotFoundError` when running script:
```
python mealpy/mealpy.py reserve foo bar sf
Traceback (most recent call last):
  File "mealpy/mealpy.py", line 229, in <module>
    cli()
...
Snipped for brevity
...
  File "mealpy/mealpy.py", line 138, in get_mealpal_credentials
    config = load_config()
  File "mealpy/mealpy.py", line 49, in load_config
    copyfile(template_config_path, config_path)
  File "/Users/ipwponies/repos/mealpy/venv/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/ipwnponies/repos/mealpy/mealpy/config.template.yaml'
```

This was introduced in PR #20, when`mealpal.py` was [moved to a package][1].

[1]: https://github.com/edmundmok/mealpy/commit/2e822639f6ddb052e4515e1557e6891ea34566e4#diff-901da7e2e7b070d849c268360f8ad25c

**Comment by ipwnponies** [comment]
While we're fixing this, I propose we become [XDG compliant][1] and put values into `$XDG_CONFIG`.
We can use the helper [`xdg` package](https://github.com/srstevenson/xdg).

[1]: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#basics
